### PR TITLE
[THS] Add "_castentityshadow" parm:

### LINKED ISSUE #65: Add parm to light "Cast entity shadows" for enable\disable local casting shadows from this light.
Adding parm "Cast entity shadows" to light in L4D or L4D2 choose allows the light to modify the direction of nearby render-to-texture shadows so that they always point away from its origin, if this is needed.

### PR DESCRIPTION
**Pull request by THS2121966**
(Describe your PR here and then fill out the checklist at the bottom)

Allows the light to modify the direction of nearby render-to-texture shadows so that they always point away from its origin.
https://youtu.be/BUYY822xm38
---

#### Does this PR close any issues?
* Close #65 

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

**Comment by Blixibon** [comment]
Sorry for the late response, but did you write this code yourself or did you get it from another source?

**Comment by THS2121966** [comment]
Yes, I created it on my own, using as reference another flag founded on "bspfile.h" "DWL_FLAGS_INAMBIENTCUBE". I understood, if flags allowed in dworldlight_t then that help me to improve worldlight.cpp for using that local shadow casting function turn on/off from light info if needed.

**Comment by Blixibon** [comment]
Where did you find `DWL_FLAGS_INAMBIENTCUBE`?

**Comment by PiMoNFeeD** [comment]
> Yes, I created it on my own, using as reference another flag founded on "bspfile.h" "DWL_FLAGS_INAMBIENTCUBE". I understood, if flags allowed in dworldlight_t then that help me to improve worldlight.cpp for using that local shadow casting function turn on/off from light info if needed.

whatever you say
image
image
you haven't changed a symbol from leaked csgo code

**Comment by THS2121966** [comment]
Okay... My fail... Just don't use that code. But adding flag and using that not a big problem. Sorry. I remembered, that I used this from a leaked code.

**Comment by Blixibon** [comment]
> Okay... My fail... Just don't use that code. But adding flag and using that not a big problem. Sorry. I remembered, that I used this from a leaked code.

I don't think I can use anything in this pull request. In fact, I don't want to risk accepting leaked code from your other pull requests either. Passing leaked code as your own is a serious violation of Mapbase's contribution guidelines, which exist for many reasons.

I understand 2-3 months have passed since you submitted this PR and there is the generous possibility that you might have simply forgotten where this code originally came from when you claimed you wrote this on your own, but **you had already claimed to have been following the contribution guidelines at the time of submission via the PR Checklist**. You should have been fully aware of the fact it was leaked code at that time.

I appreciate your enthusiasm for Mapbase, but the fact the contribution guidelines were violated so severely makes me distrust your contributions completely, regardless of whether this was done by mistake or out of malice. I'm sorry that it's come to this, but from this point forward, **I will not be accepting any of your current or future pull requests to this repository.**

You can still open issues if you wish, but pull requests will be ignored.

**Comment by THS2121966** [comment]
Okay, I understand it. Sorry for wasting your time.

**Comment by THS2121966** [comment]
I really forgot about using that leak code...

**Pull request closed without merging**
