### PR TITLE
Mapbase v7.2 Linux fixes

### PR DESCRIPTION
**Pull request by Blixibon**
This is in a separate PR until the fixes are verified.

### CODE REVIEW

**Comment by samisalreadytaken** [comment]
Probably related, this here on Linux ignores the directory (vgui/) escape

https://github.com/mapbase-source/source-sdk-2013/blob/af6f9fe5185c1425bac6394073c94be723489198/sp/src/game/client/mapbase/vscript_vgui.cpp#L430

Can be tested with
```cs
local panel = vgui.CreatePanel( "ImagePanel", vgui.GetClientDLLRootPanel(), "" );
panel.MakeReadyForUse();
panel.SetVisible( true );
panel.SetPaintEnabled( true );
panel.SetPaintBackgroundEnabled( true );
panel.SetSize( 256, 256 );
panel.SetPos( 0, 0 );
panel.SetImage( "brick/brickfloor001a", false );
```

**Comment by Blixibon** [comment]
> Probably related, this here on Linux ignores the directory (vgui/) escape
> 
> https://github.com/mapbase-source/source-sdk-2013/blob/af6f9fe5185c1425bac6394073c94be723489198/sp/src/game/client/mapbase/vscript_vgui.cpp#L430
> 
> Can be tested with
> 
> ```cs
> local panel = vgui.CreatePanel( "ImagePanel", vgui.GetClientDLLRootPanel(), "" );
> panel.MakeReadyForUse();
> panel.SetVisible( true );
> panel.SetPaintEnabled( true );
> panel.SetPaintBackgroundEnabled( true );
> panel.SetSize( 256, 256 );
> panel.SetPos( 0, 0 );
> panel.SetImage( "brick/brickfloor001a", false );
> ```

I'm not experiencing this issue on my Linux machine. When running the test code, the brick floor texture doesn't render properly due to its shader, but the directory escape successfully navigates to the file.

image

**Comment by samisalreadytaken** [comment]
Using brick material (which was a blind example) or a custom material in a custom directory under custom addon mount seems to work indeed. So I don't know what exactly is going on here when the following works only when the materials are put under vgui/. I'm unable to test this further at the moment

Screenshot_2023-10-27_22-56-26

**Comment by Blixibon** [comment]
That's fine. I'm not in a good position to spend too much time on this myself, so I've opened an issue for it (https://github.com/mapbase-source/source-sdk-2013/issues/252) that can be resolved later.

**Pull request merged**
