### PR TITLE
Sound support for vgui_movie_display

### PR DESCRIPTION
**Pull request by Alivebyte**
Working sound for vgui_movie display. Has a little sound delay when enabling panel. Has a FGD value for sound mute. Requires fgd modification.

---

#### Does this PR close any issues?
* No

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

**Comment by Blixibon** [comment]
`m_bMuted` should be true by default in order to preserve the lack of sound in existing movie panels.

Does the sound come from the `vgui_movie_display` itself or is it global?

**Comment by Alivebyte** [comment]
It's global

**Comment by Alivebyte** [comment]
And I don't think it's neccesary that m_bMuted should be true, since it always gets value from fgd where it can be defined true by default, plus there is no constructor for CMovieDisplay.

**Comment by Blixibon** [comment]
Instances of `vgui_movie_display` in existing maps will not have the `muted` keyvalue defined, therefore `m_bMuted` will not be changed from its default value. Even though I don't think `vgui_movie_display` has been used in Mapbase much and sound playback isn't exactly game-breaking, I cannot accept this PR unless existing behavior is preserved.

You could create a constructor for `CMovieDisplay` which mutes panels by default by adding `CMovieDisplay() { m_bMuted = true; }` anywhere in the class definition.

**Comment by Alivebyte** [comment]
Ok, thanks :)

**Comment by Alivebyte** [comment]
I think that's should fix the problem.

**Comment by Blixibon** [comment]
Good! I tested this locally and it seems to function as intended.

I also noticed one of the commits is from another user (rzkid). Even though they just removed a variable, can I assume you have their permission to use their work for this?

**Comment by rzkid** [comment]
Yeah, i can confirm he indeed has my permission :)

**Comment by Blixibon** [comment]
Alright, then I think this is ready to merge. It's cutting pretty close to v7.0, but there's still time and I don't think there's much risk to merging this.

Thanks for your contribution!

**Pull request merged**
