### PR TITLE
[THS] Added New Water Shader with WaterFlow from ASW.

### PR DESCRIPTION
**Pull request by THS2121966**
Tested on ths_iv_engine:
https://github.com/THS2121966/ths_iv_engine
=================================
Video demonstration:
https://youtu.be/I-wrC6q3QYo

### CODE REVIEW

**Comment by URAKOLOUY5** [comment]
Why every thing you do use [THS]? it makes no point

**Comment by THS2121966** [comment]
It is a good question. Really needed question. Next question.

**Comment by URAKOLOUY5** [comment]
It sounds so toxic. But your passion for THS makes unnecessary garbage in Mapbase. Why does everyone who will fork Mapbase need the THS references?

**Comment by THS2121966** [comment]
1) It is been a sarcasm for joke. 2) This files from my project. Blixibon can use this as reference and delete this PR. Sorry, if I offended you.

**Pull request closed without merging**
