### PR TITLE
Fix a symbol being defined twice

### PR DESCRIPTION
**Pull request by undnull**
HexEditted `particles.lib` renaming `_hypot` to `_STUB1` to avoid linker error-ing about a symbol being defined twice.  
I was unable to find any traces of `/force:multiple` in vpc_scripts though.  

---

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

**Comment by undnull** [comment]
What is that commit reference history over there

**Comment by Blixibon** [comment]
> What is that commit reference history wall over there

It's from targeting the `master` branch, which you claimed in the PR checklist you weren't doing

**Comment by undnull** [comment]
Whoops, fixed

**Comment by Blixibon** [comment]
Does this function when compiling under VS2013?

**Comment by undnull** [comment]
> Does this function when compiling under VS2013?

I don't see any reasons to fail as `particles.lib` doesn't use _hypot in any way and just embeds the whole thing. However let me check...

**Comment by undnull** [comment]
So it builds and runs on my source code tree.  
Now checking mapbase...

**Comment by undnull** [comment]
It builds and runs.

**Pull request merged**
