### PR TITLE
Sprinting fixes

### PR DESCRIPTION
**Pull request by z33ky**
I don't know if these "fixes" align with the spirit of Mapbase.

I think that "[not] swallow[ing] sprinting while jumping" is an objective improvement. Basically without this change if you're in the air, press sprint and hit the ground, you need to let go of sprint and press it again to actually start sprinting.
With this change it will "virtually depress" sprint while you cannot actually sprint, so that as soon as you are able to (i.e. when landing on ground after jumping) you will resume sprinting.

The suit-energy thing may just be a gameplay quirk and not an outright bug. It seems nonsensical to me to let the energy be drained if you're in the air - now I've just said sprinting didn't work with jumping, but oh it does if you're sprinting *before* jumping. Just not during.
So anyways, if you sprint while jumping it will drain your suit, but not actually speed you up. Again, could just be considered a gameplay quirk, though I judged it to be buggy behavior and "fixed it.

If you only want one of these changes let me know and I'll remove the other commit from this branch.

---

#### PR Checklist
- [x] **My PR follows all guidelines in the CONTRIBUTING.md file**
- [x] My PR targets a `develop` branch OR targets another branch with a specific goal in mind

### CODE REVIEW

**Comment by z33ky** [comment]
Sprinting while in the air *does* have an effect. It's barely noticeable, since airspeed is capped at 30 (by default), but it is there.
Thusly I have removed the commit that prevents draining of suit-energy while in the air.
It seems unfair that energy is drained by actual movement (e.g. falling) instead of "movement commands", but I'll leave that as-is.

I have also noticed that sprinting does not start if activated during ducking (i.e. duck, hold sprint, unduck), which I have addressed in the new commit.

**Comment by z33ky** [comment]
I've pushed a cleaner fix for resuming sprinting after ducking.

I've also noticed buggy behavior that you can keep sprinting if you fall into water (i.e. start sprinting while falling in air and it doesn't get reset when you land in water), but you cannot start sprinting while inside water. Changing behavior here seems like it would modify gameplay too much to be in accordance with Mapbase's rules. The PR keeps this behavior as-is.

**Comment by z33ky** [comment]
What is a way forward here?
To recapitulate: When jumping and then pressing sprint while still in the air, sprinting is not started once back on ground. The sprint-command has to be released and engaged again. This is addressed in the first commit, so that the player starts sprinting as soon as `CanSprint()` is `true` again (i.e. touches the ground).
Similarly sprinting can be interrupted by crouching. However, the sprinting is not resumed when uncrouching. This is addressed in the second commit.

There are further peculiarities in the movement system, which I have decided not to address for mapbase:
* suit-energy is drained from falling while sprinting
* sprinting has a very minimal effect on air-control, but since air-speed is capped at 30 it seems disproportionate to the energy that is drained
* when falling/going into water while sprinting, you can keep sprinting in water - but sprinting cannot be *started* while in water

I felt that these affect gameplay, thus are not suitable for "fixing", while the other two feel like deficiencies in the input handling, thus deserve to be addressed.
If you are unhappy with the proposed changes feel free to decline the pull request.

**Comment by Blixibon** [comment]
I apologize for taking so long to get back to this PR. Other things required my attention at the time of its opening and I haven't been able to handle contributions much over these past few months.

I tested these changes in-game and I don't think this is within Mapbase's scope. Mapbase is supposed to stay as close to the original game and its functionality as possible so that merging Mapbase would not risk unbalancing a mod or requiring users to oblige to specific changes they may not want to use. Although this is a minor change and essentially a bug fix, it changes how player input is handled and changes how suit power is drained in Half-Life 2. I think that's too significant.

Still, I greatly appreciate your continued contributions to this repository and I again apologize that it took me so long to get to this PR.

**Pull request closed without merging**
