### PR TITLE
Fixed some assertions and a crash, reactivated Advisor

### PR DESCRIPTION
**Pull request by stepa2**
Fixed player footstep override assertion
Registered previously unregistered ACT_RELOAD_AR2 activity
Made shawdow manager just skipping second shadow render in the same frame
Fixed crash when steamapicontext->SteamFriends() is null

### CODE REVIEW

**Comment by ReDucTor** [comment]
This will probably fix #18

**Comment by stepa2** [comment]
It will fix some of assertions

**Comment by stepa2** [comment]
I reactivated the Advisor (#16), replaced Advisor Shield particles (original were not published), added "loose of grip" schedule.
Known `npc_advisor` bugs:
- Player pinning has no effects and movement is lagging
- WrenchImmediate has no effects
- Advisor model has no collision and does not falls down on death

**Comment by Blixibon** [comment]
I am very disappointed that you didn't listen to me when I said Mapbase isn't going to have these things like this in my response to #16. Not to mention the fact I tried to cover this in the contribution guidelines:

```
 * A contribution must be aligned with Mapbase's goals and priorities and should not be "subjective"
   or related to a specific mod or type of mod. For example, fixing an existing issue or adding a
   new tool for mappers to use is usually fine, but adding a new custom weapon with its own assets
   is usually not fit for Mapbase.
````

This rule applies to NPCs like `npc_advisor` as well.

However, after conversations with people using Mapbase in their mods and a public poll for Mapbase users, it has been decided that `npc_advisor` will be acceptable in this case. This PR will continue to be on track to be merged in the next update, including your restored `npc_advisor` with it.

Just be more mindful next time, please.

**Comment by Blixibon** [comment]
I'm getting a compilation error when I compile this on the Release configuration:
```
2>  npc_advisor.cpp
2>c:\program files (x86)\microsoft visual studio 12.0\vc\include\crtdbg.h(264): error C2220: warning treated as error - no 'object' file generated
2>c:\program files (x86)\microsoft visual studio 12.0\vc\include\crtdbg.h(264): warning C4005: '_malloc_dbg' : macro redefinition
2>          e:\mapbase\mapbase-hl2-master\sp\src\public\tier0\memdbgon.h(176) : see previous definition of '_malloc_dbg'
```
I was planning on merging this with the next Mapbase update, but I don't know how to solve this problem myself and I am planning on releasing the next update very soon.

If this is not fixed in time, it may have to wait until another update.

**Comment by Blixibon** [comment]
I would like to apologize for at first saying that this will be in the next update, but despite the demand from some of Mapbase's users, I have decided that the advisor part of this PR will not be merged.

I'm making this decision for several reasons:

* **It sets a bad example for contributions.** Although the code in this PR mostly just restores and fixes existing code, this is a subjective contribution which violates the contribution guidelines and, since the restoration of an entire NPC would be considered a rather large contribution, it shouldn't be looked to as an example of a good contribution. It could just as easily be done in a separate mod or repo that people can decide to draw from themselves.
* **I don't have time to test it properly.** Testing this requires specific keyvalues using specific types of entities and I don't have time to go to the extra effort to make an entire map or section of a map for testing this. Not to mention the fact **it had a compile error after supposedly being ready to merge, which makes this less trustworthy.** That error has been fixed now thanks to your additional commits, but since I can't actually test this, I can't look for additional problems either.
* **This could conflict with mods which already have their own advisor code.** Those mods may very well benefit from some of the fixes in this contribution, but again, this doesn't have to be a part of Mapbase for that.
* **You did this after I specifically told you beforehand that stuff like this shouldn't be in Mapbase.** That offended me a lot, especially since it seemed as though you were just shoving it into a perfectly fine PR.

The debug assert fixes which were in the original version of this PR are fine and stable, and I would be happy to merge those. It's just the restored advisor NPC which I won't allow into Mapbase.

In order to minimize risks and give you control over your own PR, I request that you revert the advisor commits yourself. Then, I will merge this in the next update.

**Comment by Blixibon** [comment]
I recently did some experimentation with the Debug configuration for Mapbase v5.0 and I was encountering a lot of assertion failures caused by Mapbase code. I fixed a bunch of them, but I realized a few minutes after starting to fix them that a lot of them were the same asserts fixed in this PR.

I have noticed that you have not returned to this PR ever since I told you the restored advisor could not be included. I deeply apologize if you feel that I did not respect your contribution, but I want to get these debug fixes into Mapbase v5.0 and I can't merge this PR unless the advisor commits are reverted.

I already fixed a lot of the same asserts on my own and I didn't realize they were the same ones fixed in your PR until later, but I would still prefer to credit you for them and integrate some of the other fixes I didn't make which are in this PR, like the `SteamFriends()` fix in `mapbase_rpc.cpp`.

Mapbase v5.0 is planned to release at some point within the next few days. We would normally prefer to include your commits directly so you can be properly credited in the repo's history as part of the evolving Mapbase contribution etiquette, but if you do not respond to this message before that point, I will assume that you will not be able to return to this PR and I will make our combined debug fixes *(fixes I made myself which are not in your PR, fixes I made coinciding with the ones in your PR, and important fixes in your PR I didn't make)* a part of my own v5.0 commit with partial credit to you, closing this PR in the process. If you are reading this message after v5.0 is released and you are not okay with this, please reach out to me immediately.

**Comment by Blixibon** [comment]
Mapbase v5.0 has been released with some of your changes. I have given you credit in the commit message and official change lists. Thank you for your contributions.

**Pull request closed without merging**
