### PR TITLE
[THS] Improvments for compilers.

### PR DESCRIPTION
**Pull request by THS2121966**
1) func_detail_blocker
2) Toggleable Brush AO and more from:
https://github.com/DownFall-Team/DownFall/commit/8f45ed6b4270343959d83ba90a659c5b06f9d5b1

### CODE REVIEW

**Comment by THS2121966** [comment]
Tested on:
https://github.com/THS2121966/ths_iv_engine

**Comment by Blixibon** [comment]
Mapbase has borrowed changes obtained from the Downfall repo in the past *(e.g. radial fog, treesway, etc.)* and it has been considered a trusted source. Many of the changes Mapbase uses from the Downfall repo are from later Valve games, but all of them are available in the Alien Swarm SDK and have virtually no difference aside from modifications to make them work in Source 2013.

The changes in this PR are also from the Downfall repo and involve features used in later Valve games, but unlike the other changes Mapbase has borrowed, the changes in this PR are for the compile tools. These cannot be compared to the Alien Swarm SDK because the Alien Swarm SDK does not contain the source code for the compile tools.

Since the source of this code is not known and it is suspiciously similar to Valve's code, the changes in this PR may have come from a closed-source branch of VRAD and may or may not be legal to distribute in a Mapbase context. Because of this possibility and our strict stance on leaked content, this PR cannot be accepted.

I apologize for not being able to respond to this PR sooner. Please notify me if you know where this code could have come from and can prove that it's completely legal for Mapbase and its users to use.

**Comment by THS2121966** [comment]
Ok. I understand it.

**Comment by chloecormier** [comment]
Sorry for the necro, but I'm suspicious of the idea that the func_detail_blocker code is from the leak. As far as I can tell, it originated from https://github.com/wouterpleizier/source-sdk-2013/commit/804ff1c4f991b9194a1639231853b64260285acc which is from 2014 (which predates the leak of this code, as far as I'm aware?), the original repo contains no other leaked code, and the code appears to bears zero resemblance to the func_detail_blocker implementation from the CS:GO leak.

It seems like it's bespoke. That said, the AO is definitely from a leak, it literally has comments from the CS:GO team left in it, so I suspect that Downfall just merged code from a lot of different sources. But it would be nice to see func_detail_blocker support.

**Comment by Yankumo-Koishi** [comment]
> Sorry for the necro, but I'm suspicious of the idea that the func_detail_blocker code is from the leak. As far as I can tell, it originated from [wouterpleizier@804ff1c](https://github.com/wouterpleizier/source-sdk-2013/commit/804ff1c4f991b9194a1639231853b64260285acc) which is from 2014 (which predates the leak of this code, as far as I'm aware?), the original repo contains no other leaked code, and the code appears to bears zero resemblance to the func_detail_blocker implementation from the CS:GO leak.
> 
> It seems like it's bespoke. That said, the AO is definitely from a leak, it literally has comments from the CS:GO team left in it, so I suspect that Downfall just merged code from a lot of different sources. But it would be nice to see func_detail_blocker support.

TL,DR pls (sorry my English is too suck lmfao)

**Comment by Jesse-Culver** [comment]
> > Sorry for the necro, but I'm suspicious of the idea that the func_detail_blocker code is from the leak. As far as I can tell, it originated from [wouterpleizier@804ff1c](https://github.com/wouterpleizier/source-sdk-2013/commit/804ff1c4f991b9194a1639231853b64260285acc) which is from 2014 (which predates the leak of this code, as far as I'm aware?), the original repo contains no other leaked code, and the code appears to bears zero resemblance to the func_detail_blocker implementation from the CS:GO leak.
> > It seems like it's bespoke. That said, the AO is definitely from a leak, it literally has comments from the CS:GO team left in it, so I suspect that Downfall just merged code from a lot of different sources. But it would be nice to see func_detail_blocker support.
> 
> TL,DR pls (sorry my English is too suck lmfao)

They are saying that the func_detail_blocker looks to be good based on what date it was created and how it is different enough from the leaked code.

Toggleable Brush AO is from leaked CS:GO code and has comments directly from Valve's code in it and should not be added.

**Pull request closed without merging**
